name: Testes API ServeRest Cypress

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Cypress run
        uses: cypress-io/github-action@v5
        continue-on-error: true
        with:
          install-command: npm install
          start: npm start
      - name: Publish Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mochawesome-report
